.eslintrc.json, changelog.md, src/draw/DefaultDrawer.js, src/index.js, src/metadata/DefaultMetadata.js, src/parser/DefaultParser.js, src/render/DefaultRender.js, tests/unit/draw/DefaultDrawer.spec.js, tests/unit/metadata/DefaultMetadata.spec.js, tests/unit/parser/DefaultParser.spec.js, tests/unit/render/DefaultRender.spec.js
=> Feature: Write default classes structure.

.github/workflows/sonar.yml, .gitignore, README.md, package-lock.json, package.json, webpack.config.js
=> Feature: setup build

README.md, changelog.md, package-lock.json, package.json, sonar-project.properties
=> Rename project to leto-modelizer-plugin-core

.eslintrc.js
=> Set default line break to unix

changelog.md, jest.config.js, package-lock.json, package.json, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
=> Feature: Draw and UpdateComponent method in DefaultDrawer class

.github/workflows/docs.yml, changelog.md
=> Feature: generate documentation page

.github/workflows/docs.yml
=> Fix workflow to generate documentation

src/draw/DefaultDrawer.js, src/error/parseError.js, src/metadata/DefaultMetadata.js, src/models/Component.js, src/models/ComponentAttribute.js, src/models/ComponentAttributeDefinition.js, src/models/ComponentDefinition.js, src/models/ComponentDrawOption.js, src/models/ComponentLink.js, src/parser/DefaultParser.js, src/render/DefaultRender.js
=> Improve class documentation

src/metadata/DefaultMetadata.js, tests/unit/metadata/DefaultMetadata.spec.js
=> Add method `getComponentDefinitions` to DefaultMetadata

src/parser/DefaultParser.js, tests/unit/parser/DefaultParser.spec.js
=> Add isParsable method in DefaultParser

changelog.md, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
=> Make draw method call specific drawX method

.eslintrc.js, changelog.md, jest.config.js, src/draw/DefaultDrawer.js, tests/mock/D3Mock.js, tests/unit/draw/DefaultDrawer.spec.js
=> Feature: selection on click

src/draw/DefaultDrawer.js, tests/mock/D3Mock.js, tests/unit/draw/DefaultDrawer.spec.js
=> Improve templates drawing methods

.eslintrc.js
=> Remove dist folder for eslint check

README.md, changelog.md
=> Fix link of technical documenation in readme

README.md, changelog.md, src/metadata/DefaultMetadata.js, src/models/Component.js, src/models/FileInformation.js, src/parser/DefaultParser.js, src/render/DefaultRender.js, tests/unit/models/Component.spec.js, tests/unit/models/FileInformation.spec.js, tests/unit/models/FileInput.spec.js, tests/unit/render/DefaultRender.spec.js
Missing remove usage of resources in `DefaultDrawer`, it will be made in another pr.
=> Improvement: remove resources and use FileInput/FileInformation

changelog.md, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
=> Fix: Positioning of components if no container exists

changelog.md, src/models/ComponentDefinition.js, tests/unit/models/ComponentDefinition.spec.js
Add childrenTypes in ComponentDefinition's props and update tests.
=> Add childrenTypes in ComponentDefinition's props

changelog.md, demo/src/App.vue, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
Emit events on edit, select and delete
=> Feature: Emit events on edit, select and delete

changelog.md, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
Add a function that create new link between two components.
=> Feature: Action to create new link

changelog.md, src/draw/DefaultDrawer.js, src/models/Component.js, tests/unit/models/Component.spec.js
=> Feature: set/unset container attribute

changelog.md, demo/src/App.vue, demo/src/assets/data.js, src/draw/DefaultDrawer.js, src/models/Component.js, tests/mock/D3Mock.js, tests/unit/draw/DefaultDrawer.spec.js, tests/unit/models/Component.spec.js
Add feature that can add new link.
=> Feature: Add links by link definition

changelog.md, src/models/Component.js, src/models/DefaultData.js, tests/unit/models/Component.spec.js, tests/unit/models/DefaultData.spec.js
=> Improvement: remove link

src/models/DefaultData.js, tests/unit/models/DefaultData.spec.js
=> Bugfix: Fix reverse link to not reverse attribute

changelog.md, demo/package-lock.json, demo/src/DemoMetadata.js, demo/src/DemoParser.js, demo/src/DemoPlugin.js, package.json, src/draw/DefaultDrawer.js, src/models/Component.js, src/models/ComponentLink.js, tests/unit/draw/DefaultDrawer.spec.js, tests/unit/models/Component.spec.js, tests/unit/models/ComponentLink.spec.js
=> Bugfix: delete link

changelog.md, demo/package-lock.json, demo/src/App.vue, src/models/DefaultPlugin.js, src/parser/DefaultParser.js, src/render/DefaultRender.js, tests/unit/models/DefaultPlugin.spec.js, tests/unit/parser/DefaultParser.spec.js, tests/unit/render/DefaultRender.spec.js
=> Feature: save position

changelog.md, demo/src/assets/resources.js, package.json, src/draw/DefaultDrawer.js
=> Improvement: Use component templates

changelog.md, src/draw/DefaultDrawer.js
Add support for top and bottom anchors.
=> Improvement: add vertical anchors

changelog.md, src/draw/DefaultDrawer.js, tests/unit/draw/DefaultDrawer.spec.js
=> Improvement: dynamic link curve selection

changelog.md, demo/package-lock.json, demo/src/App.vue, demo/src/DemoMetadata.js, demo/src/DemoParser.js, demo/src/DemoPlugin.js, src/draw/DefaultDrawer.js, src/models/Component.js, src/models/DefaultData.js, src/render/DefaultRender.js, tests/unit/models/Component.spec.js, tests/unit/models/DefaultData.spec.js, tests/unit/render/DefaultRender.spec.js
=> Improvement: simplify container

changelog.md, demo/src/App.vue, src/draw/DefaultDrawer.js, src/models/DefaultPlugin.js, tests/unit/draw/DefaultDrawer.spec.js
=> Improvement: events

changelog.md, demo/src/DemoMetadata.js, src/draw/DefaultDrawer.js
Fix disabled style application when source can have multiple destinations.
=> Bugfix: multi-target disabled style

changelog.md, demo/src/DemoMetadata.js, src/draw/DefaultDrawer.js, src/models/ComponentAttributeDefinition.js, src/models/ComponentLinkDefinition.js, src/models/DefaultData.js, tests/unit/models/ComponentAttributeDefinition.spec.js, tests/unit/models/ComponentLinkDefinition.spec.js
=> Feature: custom link

changelog.md, src/models/DefaultPlugin.js
=> Improvement: default plugin

.eslintrc.js, README.md, changelog.md, jsdoc.config.json, package-lock.json, package.json, src/draw/DefaultDrawer.js, src/error/ParseError.js, src/metadata/DefaultMetadata.js, src/models/Component.js, src/models/ComponentAttribute.js, src/models/ComponentAttributeDefinition.js, src/models/ComponentDefinition.js, src/models/ComponentDrawOption.js, src/models/ComponentLink.js, src/models/ComponentLinkDefinition.js, src/models/DefaultData.js, src/models/DefaultPlugin.js, src/models/FileInformation.js, src/models/FileInput.js, src/parser/DefaultParser.js, src/render/DefaultRender.js
=> Improvement: replace esdoc to jsdoc

changelog.md, src/render/DefaultRender.js, tests/unit/render/DefaultRender.spec.js
=> Improvement: Pretty configuration

changelog.md, cypress/e2e/container-resizing.feature, cypress/e2e/delete.feature, cypress/e2e/drag-and-drop.feature, cypress/e2e/link-creation.feature, cypress/e2e/renderer.feature, cypress/e2e/selection.feature, cypress/support/step_definitions/event.js, cypress/support/step_definitions/html.js, src/draw/DefaultDrawer.js
=> Improvement: complete e2e tests

changelog.md, src/draw/DefaultDrawer.js
=> Bugfix: zoom behavior

changelog.md, demo/src/DemoMetadata.js, demo/src/DemoParser.js, demo/src/assets/resources.js, src/draw/DefaultDrawer.js, src/models/Component.js, src/models/ComponentAttribute.js, src/models/ComponentAttributeDefinition.js, tests/unit/models/Component.spec.js, tests/unit/models/ComponentAttribute.spec.js, tests/unit/models/ComponentAttributeDefinition.spec.js
=> Feature: Add errors detection in Component.

changelog.md, package-lock.json, package.json, src/models/ComponentAttributeDefinition.js, src/models/ComponentDefinition.js, tests/unit/models/ComponentAttributeDefinition.spec.js, tests/unit/models/ComponentDefinition.spec.js
=> Feature: add properties for component and attribute

changelog.md, src/draw/DefaultDrawer.js
=> Feature: improve component template

changelog.md, demo/src/DemoMetadata.js, src/draw/DefaultDrawer.js, src/models/ComponentLinkDefinition.js, src/models/DefaultData.js, tests/unit/models/DefaultData.spec.js
=> Feature:  Draw arrow markers on links.

changelog.md, src/models/Component.js, src/models/ComponentAttribute.js, tests/unit/models/Component.spec.js
=> Fix hasError when not required attribute has empty value

.github/workflows/CI.yml, .github/workflows/clean.yml, .github/workflows/stat.yml
=> Update github workflow

changelog.md, src/models/DefaultConfiguration.js, src/models/DefaultPlugin.js, tests/unit/models/DefaultConfiguration.spec.js, tests/unit/models/DefaultPlugin.spec.js
=> Feature: add plugin configuration

.github/workflows/CI.yml, .github/workflows/clean.yml, .github/workflows/stat.yml, README.md
=> Improve CI

changelog.md, src/models/DefaultPlugin.js, src/parser/DefaultParser.js, tests/unit/models/DefaultPlugin.spec.js, tests/unit/parser/DefaultParser.spec.js
=> Feature: get models

changelog.md, src/index.js, tests/unit/index.spec.js
Export missing `DefaultConfiguration` class in library.
=> Bugfix: export default configuration

changelog.md, cypress/e2e/container-resizing.feature, cypress/support/step_definitions/event.js, src/draw/DefaultDrawer.js, src/models/ComponentDefinition.js, src/models/ComponentDrawOption.js, src/models/EventLog.js, tests/unit/models/ComponentDrawOption.spec.js, tests/unit/render/DefaultRender.spec.js
Adding a new feature It allows you to manually resize the container component.
=> Feature: Manual resizing of container component

changelog.md, cypress/e2e/automatic-layout.feature, cypress/e2e/drag-and-drop.feature, cypress/support/step_definitions/html.js, demo/src/App.vue, guides/migrations/0.18.0_to_0.X.0.md, package-lock.json, package.json, src/draw/DefaultDrawer.js, src/draw/DefaultLayout.js, src/draw/ElkLayout.js, src/models/DefaultPlugin.js, tests/unit/draw/DefaultDrawer.spec.js, tests/unit/draw/DefaultLayout.spec.js, tests/unit/draw/ElkLayout.spec.js, tests/unit/models/DefaultPlugin.spec.js
I added a method to the `DefaultPlugin` class to trigger automatic layout for the diagram using `elkjs`.
I also created a Cypress  step definition to test HTML attribute values (may be useful to others).
=> Feature: Automatic diagram layout

guides/migrations/0.18.0_to_0.X.0.md
=> Update migration guide

changelog.md, package-lock.json, src/draw/DefaultDrawer.js, src/models/DefaultPlugin.js, tests/unit/draw/DefaultDrawer.spec.js
=> Reset draw actions

README.md
Improve plugin configuration doc in README.md
=> Improve plugin configuration doc in README.md

.github/workflows/docs.yml, changelog.md
Fix error when docs is generating.
=> Bugfix: docs generation

changelog.md, demo/package-lock.json, src/draw/render/LinkRenderer.js, src/models/ComponentLink.js, src/models/DefaultData.js, tests/unit/models/ComponentLink.spec.js, tests/unit/models/DefaultData.spec.js
=> Bugfix: reverse link display

changelog.md, demo/src/App.vue, demo/src/assets/resources.js, guides/svg/template.md, src/draw/DefaultDrawer.js, src/draw/render/ComponentRenderer.js, src/draw/render/LinkRenderer.js, src/models/DefaultPlugin.js
=> Feature: export svg

changelog.md, guides/documentations/essentials.md, src/models/ComponentAttributeDefinition.js, src/models/ComponentDefinition.js, tests/unit/models/ComponentAttributeDefinition.spec.js, tests/unit/models/ComponentDefinition.spec.js
=> Feature: add new fields

changelog.md, src/draw/DefaultDrawer.js, src/draw/render/ComponentRenderer.js, src/draw/render/LinkRenderer.js
=> Feature: permit to override renderer in drawer

changelog.md, src/draw/DefaultDrawer.js, src/models/DefaultPlugin.js
=> Bugfix: export svg bad id

changelog.md, guides/documentations/configuration.md, guides/migrations/0.24.0_to_0.25.0.md, src/models/Component.js, src/models/ComponentAttribute.js, src/models/DefaultConfiguration.js, src/models/ParserLog.js, tests/unit/models/Component.spec.js, tests/unit/models/ComponentAttribute.spec.js, tests/unit/models/DefaultConfiguration.spec.js, tests/unit/models/ParserLog.spec.js
=> Feature: i18n configuration

changelog.md, src/models/Component.js, src/models/ComponentAttribute.js, tests/unit/models/Component.spec.js, tests/unit/models/ComponentAttribute.spec.js
=> Bugfix: required attributes

.github/workflows/publish.yml, changelog.md, package-lock.json, package.json
=> Feature: publish to npm

.github/workflows/publish.yml, changelog.md
=> Bugfix: publish

.github/workflows/publish.yml
=> Try to fix publishing error

.github/workflows/publish.yml
=> Fix npm version

.github/workflows/publish.yml
=> Fix publishing to npm
